### ISSUE TITLE
Calling bottle :unneeded is deprecated!

### ISSUE THREAD

**Issue by isurugiu** [kwilczynski/homebrew-pkenv#5]
## Description

_Problem description goes here_
`brew outdated` was stopped by `Error: Too many open files`. Running `brew outdated` again throws the following error:
```
➜  ~ brew outdated
Warning: Calling bottle :unneeded is deprecated! There is no replacement.
Please report this issue to the kwilczynski/pkenv tap (not Homebrew/brew or Homebrew/core):
  /home/linuxbrew/.linuxbrew/Homebrew/Library/Taps/kwilczynski/homebrew-pkenv/Formula/pkenv.rb:8
```
## Context and Logs
```
==> Pouring ruby-build--20211019.all.bottle.tar.gz
🍺  /home/linuxbrew/.linuxbrew/Cellar/ruby-build/20211019: 545 files, 292.7KB
Removing: /home/linuxbrew/.linuxbrew/Cellar/ruby-build/20210928... (542 files, 290.7KB)
Removing: /home/iulian/.cache/Homebrew/ruby-build--20210928... (56.2KB)
Error: Too many open files
➜  ~ brew upgrade
Warning: Calling bottle :unneeded is deprecated! There is no replacement.
Please report this issue to the kwilczynski/pkenv tap (not Homebrew/brew or Homebrew/core):
  /home/linuxbrew/.linuxbrew/Homebrew/Library/Taps/kwilczynski/homebrew-pkenv/Formula/pkenv.rb:8

➜  ~ brew outdated
Warning: Calling bottle :unneeded is deprecated! There is no replacement.
Please report this issue to the kwilczynski/pkenv tap (not Homebrew/brew or Homebrew/core):
  /home/linuxbrew/.linuxbrew/Homebrew/Library/Taps/kwilczynski/homebrew-pkenv/Formula/pkenv.rb:8
```
  
Parameter | Value
--------- | ------------------
**macOS version:**       | It's not MacOS, I'm running under Ubuntu 20.04.3
**Homebrew version:**   | 3.3.2

**Build logs:** _Link to public gist created with `brew gist-logs my-formula`_

**Comment by kwilczynski** [comment]
Hi @isurugiu,

Thank you for detailed report and sorry that you are having issues! I have one other report of this problem: https://github.com/kwilczynski/homebrew-pkenv/issues/3; 

Let me update the formula so that everything works as expected. There is a Pull Request that @bennesp kindly submitted earlier at https://github.com/kwilczynski/homebrew-pkenv/pull/4, and it would resolve this problem.

Krzysztof

**Comment by kwilczynski** [comment]
Closed in #4.

**Comment by kwilczynski** [comment]
Hi @isurugiu,

All fixes and updated merged! Thank you again!

I also updated the formula so that it would install pkenv version 0.5.3 as per the upstream release, as per: https://github.com/kwilczynski/homebrew-pkenv/commit/6d88867099c6c9fb1fae46d450a40d1953854e38

Krzysztof

**Comment by isurugiu** [comment]
Worked. :bowing_man:

**Comment by kwilczynski** [comment]
Hi @isurugiu,

Glad to hear! There might have been a small hiccup to update the tap/formula, since I moved to `main` as the main repository branch name. You might have had to run `brew tap --repair`. Sorry about this!

There is one more thing I've noticed in your issue report: `Error: Too many open files`

This is a known issue on Linux with Linuxbrew where default limits are rather conservative. If you are using `systemd` based system, then you can add the following so that your user has slightly higher limits:

```bash
$ cat /etc/systemd/user.conf.d/limits.conf
[Manager]
DefaultLimitNOFILE=65535:131072
```

See [systemd-system.conf(5)](https://www.man7.org/linux/man-pages/man5/user.conf.d.5.html) for more details.

Krzysztof
